/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapp;

/**
 *
 * @author utpl-4
 */
public class bill extends javax.swing.JFrame {

    /**
     * Creates new form bill
     */
    public bill() {
        initComponents();
    }
    //declareing the multiple data we want to place to thids screen
    String name,mobile,email,address,city,state,zipcode,country,cardname,cardnum,amount,chi1,quiona1,pan1,exp1,san1;
      public bill(String p1,String p2,String p3,String p4,String p5,String p6,String p7,String p8,String p9,String p10,String p11,String p12,String p13,String p14,String p15,String p16){
        initComponents();
        
        cusName.setText(p1);
        cusMobile.setText(p2);
        cusEmail.setText(p3);
        Address.setText(p4+","+p5+","+p6+","+p8+","+p7+".");
        AmountRupees.setText(p9);
        jLabel10.setText(p10);
        jLabel11.setText(p11);
        OrderItem1.setText(p12);
        OrderItem2.setText(p13);
        OrderItem3.setText(p14);
        OrderItem4.setText(p15);
        OrderItem5.setText(p16);
      }

    bill(String msg) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        contact = new javax.swing.JLabel();
        cusName = new javax.swing.JLabel();
        cusMobile = new javax.swing.JLabel();
        cusEmail = new javax.swing.JLabel();
        cusAddress = new javax.swing.JLabel();
        cusBill = new javax.swing.JLabel();
        Address = new javax.swing.JLabel();
        AmountRupees = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        conformToPay = new javax.swing.JButton();
        Rupees = new javax.swing.JLabel();
        OrderItems = new javax.swing.JLabel();
        OrderItem1 = new javax.swing.JLabel();
        OrderItem2 = new javax.swing.JLabel();
        OrderItem3 = new javax.swing.JLabel();
        OrderItem4 = new javax.swing.JLabel();
        OrderItem5 = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(33, 148, 180));

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(249, 239, 239));
        jLabel1.setText("7 FOOD COURT ORDERING SYSTEM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(296, 296, 296)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(236, 224, 240));

        contact.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        contact.setForeground(new java.awt.Color(8, 14, 136));
        contact.setText("Contact");

        cusName.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N

        cusMobile.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N

        cusEmail.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N

        cusAddress.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        cusAddress.setForeground(new java.awt.Color(8, 14, 136));
        cusAddress.setText("Address");

        cusBill.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        cusBill.setForeground(new java.awt.Color(8, 14, 136));
        cusBill.setText("Bill Payment");

        Address.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N

        AmountRupees.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        AmountRupees.setForeground(new java.awt.Color(203, 7, 7));

        jLabel10.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(182, 7, 7));

        jLabel11.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(226, 13, 13));

        conformToPay.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        conformToPay.setForeground(new java.awt.Color(10, 55, 16));
        conformToPay.setText("Conform To Pay");
        conformToPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conformToPayActionPerformed(evt);
            }
        });

        Rupees.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        Rupees.setForeground(new java.awt.Color(14, 81, 25));
        Rupees.setText("Rs:");

        OrderItems.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        OrderItems.setForeground(new java.awt.Color(8, 14, 136));
        OrderItems.setText("Order Items");

        cancelButton.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(10, 55, 16));
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        backButton.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        backButton.setForeground(new java.awt.Color(10, 55, 16));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(OrderItem1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cusMobile)
                                            .addComponent(contact)
                                            .addComponent(cusName)
                                            .addComponent(cusEmail))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(175, 175, 175)
                                                .addComponent(cusAddress))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(0, 121, Short.MAX_VALUE)
                                                .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(72, 72, 72)
                                                .addComponent(Rupees))))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(OrderItems)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(OrderItem3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(backButton)
                                .addGap(63, 63, 63)
                                .addComponent(cancelButton)
                                .addGap(25, 25, 25)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(conformToPay)
                            .addComponent(cusBill)
                            .addComponent(AmountRupees)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(254, 254, 254))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OrderItem5)
                            .addComponent(OrderItem4)
                            .addComponent(OrderItem2))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(contact)
                            .addComponent(cusBill)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cusAddress)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(cusName)
                        .addGap(18, 18, 18)
                        .addComponent(cusMobile)
                        .addGap(18, 18, 18)
                        .addComponent(cusEmail))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(Rupees))
                                .addGap(18, 18, 18)
                                .addComponent(AmountRupees))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(OrderItems))))
                .addGap(18, 18, 18)
                .addComponent(OrderItem1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(OrderItem2)
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conformToPay)
                    .addComponent(OrderItem3)
                    .addComponent(cancelButton)
                    .addComponent(backButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(OrderItem4)
                .addGap(18, 18, 18)
                .addComponent(OrderItem5)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void conformToPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conformToPayActionPerformed
        // TODO add your handling code here:
        
        String msg = Address.getText();
        String name = cusName.getText();
        String mobile = cusMobile.getText();
        String email = cusEmail.getText();
        new done(msg,name,mobile,email).setVisible(true);
        
    }//GEN-LAST:event_conformToPayActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
         setVisible(false);
         Menu ob=new Menu();
         ob.setVisible(true);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
         setVisible(false);
         checkout ob=new checkout();
         ob.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address;
    private javax.swing.JLabel AmountRupees;
    private javax.swing.JLabel OrderItem1;
    private javax.swing.JLabel OrderItem2;
    private javax.swing.JLabel OrderItem3;
    private javax.swing.JLabel OrderItem4;
    private javax.swing.JLabel OrderItem5;
    private javax.swing.JLabel OrderItems;
    private javax.swing.JLabel Rupees;
    private javax.swing.JButton backButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton conformToPay;
    private javax.swing.JLabel contact;
    private javax.swing.JLabel cusAddress;
    private javax.swing.JLabel cusBill;
    private javax.swing.JLabel cusEmail;
    private javax.swing.JLabel cusMobile;
    private javax.swing.JLabel cusName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
