/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapp;

/**
 *
 * @author utpl-4
 */
public class checkout extends javax.swing.JFrame {

    /**
     * Creates new form checkout
     */
    public checkout() {
        initComponents();
    }
    String msg,chi1,quiona1,pan1,exp1,san1;
    public checkout(String para,String p1,String p2,String p3,String p4,String p5){
        initComponents();
        //it is used to take the value from the previous screen to this screen.
        rupees.setText(para);
        purchacesummaryfield1.setText(p1);
        purchacesummaryfield2.setText(p2);
        purchacesummaryfield3.setText(p3);
        purchacesummaryfield4.setText(p4);
        purchacesummaryfield4.setText(p5);
 
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        checkout = new javax.swing.JLabel();
        billingcontact = new javax.swing.JLabel();
        purchacesummary = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        mobileno = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        nametextfield = new javax.swing.JTextField();
        mobilenoTextfield = new javax.swing.JTextField();
        emailtextfield = new javax.swing.JTextField();
        rupees = new javax.swing.JLabel();
        billingaddress = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        city = new javax.swing.JLabel();
        state = new javax.swing.JLabel();
        zipcode = new javax.swing.JLabel();
        country = new javax.swing.JLabel();
        addresstext = new javax.swing.JTextField();
        countrytext = new javax.swing.JTextField();
        amount = new javax.swing.JLabel();
        paywithcards = new javax.swing.JLabel();
        nameontheCard = new javax.swing.JLabel();
        cardTextfield = new javax.swing.JTextField();
        cardNumber = new javax.swing.JLabel();
        cardNumberField = new javax.swing.JTextField();
        expiry = new javax.swing.JLabel();
        monthCombobox = new javax.swing.JComboBox<>();
        yesrCombobox = new javax.swing.JComboBox<>();
        cvv = new javax.swing.JLabel();
        cvvText = new javax.swing.JTextField();
        paybutton = new javax.swing.JButton();
        cityText = new javax.swing.JTextField();
        stateText = new javax.swing.JTextField();
        zipcodeText = new javax.swing.JTextField();
        backbutton = new javax.swing.JButton();
        purchacesummaryfield1 = new javax.swing.JLabel();
        purchacesummaryfield2 = new javax.swing.JLabel();
        purchacesummaryfield3 = new javax.swing.JLabel();
        purchacesummaryfield4 = new javax.swing.JLabel();
        purchacesummaryfield5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(41, 47, 46));

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 250, 250));
        jLabel1.setText("7 FOOD COURT ORDERING SYSTEM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(349, 349, 349)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(160, 180, 175));

        checkout.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        checkout.setForeground(new java.awt.Color(249, 247, 247));
        checkout.setText("CHECKOUT");

        billingcontact.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        billingcontact.setForeground(new java.awt.Color(13, 11, 194));
        billingcontact.setText("Billing Contact");

        purchacesummary.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        purchacesummary.setForeground(new java.awt.Color(8, 19, 204));
        purchacesummary.setText("Purchase Summary.");

        name.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        name.setForeground(new java.awt.Color(74, 5, 5));
        name.setText("Name:");

        mobileno.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        mobileno.setForeground(new java.awt.Color(74, 5, 5));
        mobileno.setText("Mobile Number:");

        email.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        email.setForeground(new java.awt.Color(74, 5, 5));
        email.setText("Email:");

        nametextfield.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        nametextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nametextfieldActionPerformed(evt);
            }
        });

        mobilenoTextfield.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N

        emailtextfield.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N

        rupees.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        rupees.setForeground(new java.awt.Color(141, 11, 11));

        billingaddress.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        billingaddress.setForeground(new java.awt.Color(23, 27, 151));
        billingaddress.setText("Billing Address");

        address.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        address.setForeground(new java.awt.Color(74, 5, 5));
        address.setText("Address:");

        city.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        city.setForeground(new java.awt.Color(74, 5, 5));
        city.setText("City:");

        state.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        state.setForeground(new java.awt.Color(74, 5, 5));
        state.setText("State:");

        zipcode.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        zipcode.setForeground(new java.awt.Color(74, 5, 5));
        zipcode.setText("ZipCode:");

        country.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        country.setForeground(new java.awt.Color(74, 5, 5));
        country.setText("Country:");

        addresstext.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N

        countrytext.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N

        amount.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        amount.setForeground(new java.awt.Color(56, 61, 208));
        amount.setText("Amount:");

        paywithcards.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        paywithcards.setForeground(new java.awt.Color(9, 8, 204));
        paywithcards.setText("Pay With Credit/Debit Card");

        nameontheCard.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        nameontheCard.setForeground(new java.awt.Color(74, 5, 5));
        nameontheCard.setText("Name On The Card:");

        cardNumber.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        cardNumber.setForeground(new java.awt.Color(74, 5, 5));
        cardNumber.setText("Card Number:");

        expiry.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        expiry.setForeground(new java.awt.Color(74, 5, 5));
        expiry.setText("Expiry:");

        monthCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "month", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        yesrCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "year", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34" }));

        cvv.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        cvv.setForeground(new java.awt.Color(74, 5, 5));
        cvv.setText("CVV");

        paybutton.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        paybutton.setForeground(new java.awt.Color(184, 2, 2));
        paybutton.setText("PAY");
        paybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paybuttonActionPerformed(evt);
            }
        });

        cityText.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N

        stateText.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N

        zipcodeText.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N

        backbutton.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        backbutton.setForeground(new java.awt.Color(184, 2, 2));
        backbutton.setText("Back");
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });

        purchacesummaryfield1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        purchacesummaryfield1.setForeground(new java.awt.Color(20, 17, 96));

        purchacesummaryfield2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        purchacesummaryfield2.setForeground(new java.awt.Color(20, 17, 96));

        purchacesummaryfield3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        purchacesummaryfield3.setForeground(new java.awt.Color(20, 17, 96));

        purchacesummaryfield4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        purchacesummaryfield4.setForeground(new java.awt.Color(20, 17, 96));

        purchacesummaryfield5.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        purchacesummaryfield5.setForeground(new java.awt.Color(20, 17, 96));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(email)
                                .addComponent(mobileno)
                                .addComponent(name))
                            .addComponent(billingcontact))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(purchacesummary)
                                .addGap(242, 242, 242))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(emailtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(paybutton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(25, 25, 25))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(cvv)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cvvText, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(countrytext, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(addresstext, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(276, 276, 276)
                                                        .addComponent(amount))
                                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(nametextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                                        .addComponent(mobilenoTextfield, javax.swing.GroupLayout.Alignment.LEADING)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(purchacesummaryfield1)
                                                    .addComponent(rupees)
                                                    .addComponent(purchacesummaryfield2)
                                                    .addComponent(purchacesummaryfield3)
                                                    .addComponent(purchacesummaryfield4)
                                                    .addComponent(purchacesummaryfield5))))
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(503, 503, 503)
                            .addComponent(checkout))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(billingaddress)
                                    .addGap(681, 681, 681))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(city)
                                        .addComponent(address)
                                        .addComponent(state)
                                        .addComponent(zipcode)
                                        .addComponent(country))
                                    .addGap(55, 55, 55)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(stateText, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cityText, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(zipcodeText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(298, 298, 298)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(expiry)
                                        .addComponent(cardNumber)
                                        .addComponent(nameontheCard))
                                    .addGap(4, 4, 4)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cardTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(monthCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(yesrCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(cardNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(paywithcards)
                                    .addGap(27, 27, 27))))))
                .addGap(90, 90, 90))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(backbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkout)
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(billingcontact)
                    .addComponent(purchacesummary))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(countrytext, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(country)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(name)
                                    .addComponent(nametextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(mobileno)
                                    .addComponent(mobilenoTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(email)
                                    .addComponent(emailtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(billingaddress))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(purchacesummaryfield1)
                                .addGap(18, 18, 18)
                                .addComponent(purchacesummaryfield2)
                                .addGap(18, 18, 18)
                                .addComponent(purchacesummaryfield3)
                                .addGap(18, 18, 18)
                                .addComponent(purchacesummaryfield4)
                                .addGap(18, 18, 18)
                                .addComponent(purchacesummaryfield5)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(address)
                                            .addComponent(addresstext, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(amount)
                                            .addComponent(rupees))
                                        .addGap(61, 61, 61)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(city)
                                    .addComponent(cityText, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cardTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nameontheCard))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(state)
                                    .addComponent(stateText, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cardNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cardNumber))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(zipcode)
                                    .addComponent(zipcodeText, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(monthCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(yesrCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(expiry))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cvvText, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cvv))
                                .addGap(37, 37, 37))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(paywithcards)))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(backbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(paybutton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nametextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nametextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nametextfieldActionPerformed

    private void paybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paybuttonActionPerformed
        // TODO add your handling code here:
        
        //it is used to the multiple values to place another screen
       String name = nametextfield.getText();
       String mobile = mobilenoTextfield.getText();
       String email = emailtextfield.getText();
       String address = addresstext.getText();
       String city = cityText.getText();
       String state = stateText.getText();
       String zipcode = countrytext.getText();
       String country = zipcodeText.getText();
       String cardname = cardTextfield.getText();
       String cardnum = cardNumberField.getText();
       String chi1= purchacesummaryfield1.getText();
       String quiona1= purchacesummaryfield2.getText();
       String pan1= purchacesummaryfield3.getText();
       String exp1= purchacesummaryfield4.getText();
       String san1= purchacesummaryfield5.getText();
       String amount= rupees.getText();
       new bill(name,mobile,email,address,city,state,zipcode,country,cardname,cardnum,amount,chi1,quiona1,pan1,exp1,san1).setVisible(true);
      
        
        
        
    }//GEN-LAST:event_paybuttonActionPerformed

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        // TODO add your handling code here:
        
        setVisible(false);
        Menu ob=new Menu();
        ob.setVisible(true);
        
    }//GEN-LAST:event_backbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new checkout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address;
    private javax.swing.JTextField addresstext;
    private javax.swing.JLabel amount;
    private javax.swing.JButton backbutton;
    private javax.swing.JLabel billingaddress;
    private javax.swing.JLabel billingcontact;
    private javax.swing.JLabel cardNumber;
    private javax.swing.JTextField cardNumberField;
    private javax.swing.JTextField cardTextfield;
    private javax.swing.JLabel checkout;
    private javax.swing.JLabel city;
    private javax.swing.JTextField cityText;
    private javax.swing.JLabel country;
    private javax.swing.JTextField countrytext;
    private javax.swing.JLabel cvv;
    private javax.swing.JTextField cvvText;
    private javax.swing.JLabel email;
    private javax.swing.JTextField emailtextfield;
    private javax.swing.JLabel expiry;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel mobileno;
    private javax.swing.JTextField mobilenoTextfield;
    private javax.swing.JComboBox<String> monthCombobox;
    private javax.swing.JLabel name;
    private javax.swing.JLabel nameontheCard;
    private javax.swing.JTextField nametextfield;
    private javax.swing.JButton paybutton;
    private javax.swing.JLabel paywithcards;
    private javax.swing.JLabel purchacesummary;
    private javax.swing.JLabel purchacesummaryfield1;
    private javax.swing.JLabel purchacesummaryfield2;
    private javax.swing.JLabel purchacesummaryfield3;
    private javax.swing.JLabel purchacesummaryfield4;
    private javax.swing.JLabel purchacesummaryfield5;
    private javax.swing.JLabel rupees;
    private javax.swing.JLabel state;
    private javax.swing.JTextField stateText;
    private javax.swing.JComboBox<String> yesrCombobox;
    private javax.swing.JLabel zipcode;
    private javax.swing.JTextField zipcodeText;
    // End of variables declaration//GEN-END:variables
}
