/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapp;

/**
 *
 * @author utpl-4
 */
public class Menu extends myacccount {
    //the variables declared as a private it can be accessed with in the class one out side class can't use("Encapsulation")
    //food iteams and price declared here.
    
    
   //private double chicken = 7;
    //private double quino =12;
   //private double pancake =15.50;
    //private double Expresso=10;
    //private double sandwitch=5;
   
    private double  fooditems[]={7,12,15.50,10,5};   //declareing with in the array
    
    

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        choosecusine = new javax.swing.JLabel();
        cusinetypes = new javax.swing.JComboBox<>();
        sno = new javax.swing.JLabel();
        item = new javax.swing.JLabel();
        unitprice = new javax.swing.JLabel();
        sno1 = new javax.swing.JLabel();
        quantity = new javax.swing.JLabel();
        sno2 = new javax.swing.JLabel();
        sno3 = new javax.swing.JLabel();
        sno4 = new javax.swing.JLabel();
        sno5 = new javax.swing.JLabel();
        unitpricetext1 = new javax.swing.JTextField();
        unitpricetext2 = new javax.swing.JTextField();
        unitpricetext3 = new javax.swing.JTextField();
        unitpricetext4 = new javax.swing.JTextField();
        unitpricetext5 = new javax.swing.JTextField();
        subtotal = new javax.swing.JLabel();
        subtotaltext1 = new javax.swing.JTextField();
        subtotaltext2 = new javax.swing.JTextField();
        subtotaltext3 = new javax.swing.JTextField();
        subtotaltext4 = new javax.swing.JTextField();
        subtotaltext5 = new javax.swing.JTextField();
        ordertotal = new javax.swing.JLabel();
        ordertotaltextfield = new javax.swing.JTextField();
        checkoutbutton = new javax.swing.JButton();
        calculatebutton = new javax.swing.JButton();
        resetbutton = new javax.swing.JButton();
        backbutton = new javax.swing.JButton();
        quantitycombo1 = new javax.swing.JComboBox<>();
        quantitycombo2 = new javax.swing.JComboBox<>();
        quantitycombo3 = new javax.swing.JComboBox<>();
        quantitycombo4 = new javax.swing.JComboBox<>();
        quantitycombo5 = new javax.swing.JComboBox<>();
        orderstatus = new javax.swing.JLabel();
        applycouponcode = new javax.swing.JTextField();
        chickenitem = new javax.swing.JCheckBox();
        quionaitem = new javax.swing.JCheckBox();
        pancakeitem = new javax.swing.JCheckBox();
        expressoitem = new javax.swing.JCheckBox();
        sandwitchitem = new javax.swing.JCheckBox();
        chickenorderstatus = new javax.swing.JLabel();
        quionaitemstatus = new javax.swing.JLabel();
        pancakeitemstatus = new javax.swing.JLabel();
        expressoitemstatus = new javax.swing.JLabel();
        sandwitchitemstatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(103, 189, 212));

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(155, 14, 14));
        jLabel1.setText("7 FOOD COURT ORDERING SYSTEM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(503, 503, 503))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(157, 188, 159));

        choosecusine.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        choosecusine.setText("Choose Cusine:");

        cusinetypes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "American", "Chainese", "South Indian", "North Indian" }));
        cusinetypes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusinetypesActionPerformed(evt);
            }
        });

        sno.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        sno.setForeground(new java.awt.Color(140, 5, 5));
        sno.setText("S.no");

        item.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        item.setForeground(new java.awt.Color(140, 5, 5));
        item.setText("ITEM");

        unitprice.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        unitprice.setForeground(new java.awt.Color(140, 5, 5));
        unitprice.setText("Unit Price");

        sno1.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        sno1.setForeground(new java.awt.Color(21, 18, 82));
        sno1.setText("1");

        quantity.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        quantity.setForeground(new java.awt.Color(140, 5, 5));
        quantity.setText("QTY");

        sno2.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        sno2.setForeground(new java.awt.Color(20, 17, 96));
        sno2.setText("2");

        sno3.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        sno3.setForeground(new java.awt.Color(20, 17, 96));
        sno3.setText("3");

        sno4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        sno4.setForeground(new java.awt.Color(20, 17, 96));
        sno4.setText("4");

        sno5.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        sno5.setForeground(new java.awt.Color(20, 17, 96));
        sno5.setText("5");

        unitpricetext1.setEditable(false);

        unitpricetext2.setEditable(false);
        unitpricetext2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unitpricetext2ActionPerformed(evt);
            }
        });

        unitpricetext3.setEditable(false);
        unitpricetext3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unitpricetext3ActionPerformed(evt);
            }
        });

        unitpricetext4.setEditable(false);
        unitpricetext4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unitpricetext4ActionPerformed(evt);
            }
        });

        unitpricetext5.setEditable(false);
        unitpricetext5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unitpricetext5ActionPerformed(evt);
            }
        });

        subtotal.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        subtotal.setForeground(new java.awt.Color(140, 5, 5));
        subtotal.setText("Sub Total");

        subtotaltext1.setEditable(false);

        subtotaltext2.setEditable(false);
        subtotaltext2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtotaltext2ActionPerformed(evt);
            }
        });

        subtotaltext3.setEditable(false);
        subtotaltext3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtotaltext3ActionPerformed(evt);
            }
        });

        subtotaltext4.setEditable(false);
        subtotaltext4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtotaltext4ActionPerformed(evt);
            }
        });

        subtotaltext5.setEditable(false);
        subtotaltext5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtotaltext5ActionPerformed(evt);
            }
        });

        ordertotal.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        ordertotal.setForeground(new java.awt.Color(140, 5, 5));
        ordertotal.setText("Order Total:");

        ordertotaltextfield.setEditable(false);
        ordertotaltextfield.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        ordertotaltextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordertotaltextfieldActionPerformed(evt);
            }
        });

        checkoutbutton.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        checkoutbutton.setForeground(new java.awt.Color(140, 5, 5));
        checkoutbutton.setText("Checkout");
        checkoutbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutbuttonActionPerformed(evt);
            }
        });

        calculatebutton.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        calculatebutton.setForeground(new java.awt.Color(140, 5, 5));
        calculatebutton.setText("Calculate");
        calculatebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculatebuttonActionPerformed(evt);
            }
        });

        resetbutton.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        resetbutton.setForeground(new java.awt.Color(140, 5, 5));
        resetbutton.setText("Reset");
        resetbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbuttonActionPerformed(evt);
            }
        });

        backbutton.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        backbutton.setForeground(new java.awt.Color(6, 78, 7));
        backbutton.setText("Back");
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });

        quantitycombo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));
        quantitycombo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantitycombo1ActionPerformed(evt);
            }
        });

        quantitycombo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));
        quantitycombo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantitycombo2ActionPerformed(evt);
            }
        });

        quantitycombo3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));
        quantitycombo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantitycombo3ActionPerformed(evt);
            }
        });

        quantitycombo4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));

        quantitycombo5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));

        orderstatus.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        orderstatus.setForeground(new java.awt.Color(140, 5, 5));
        orderstatus.setText("Order status");
        orderstatus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        applycouponcode.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        applycouponcode.setText("Apply Coupon Code");

        chickenitem.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        chickenitem.setForeground(new java.awt.Color(20, 17, 96));
        chickenitem.setText("Chickenburger with bacon");
        chickenitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chickenitemActionPerformed(evt);
            }
        });

        quionaitem.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        quionaitem.setForeground(new java.awt.Color(20, 17, 96));
        quionaitem.setText("Quiona and kale");
        quionaitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quionaitemActionPerformed(evt);
            }
        });

        pancakeitem.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        pancakeitem.setForeground(new java.awt.Color(20, 17, 96));
        pancakeitem.setText("Pan cakes with maple syrup");

        expressoitem.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        expressoitem.setForeground(new java.awt.Color(20, 17, 96));
        expressoitem.setText("Expresso");

        sandwitchitem.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        sandwitchitem.setForeground(new java.awt.Color(20, 17, 96));
        sandwitchitem.setText("sandwitch");
        sandwitchitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sandwitchitemActionPerformed(evt);
            }
        });

        chickenorderstatus.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        chickenorderstatus.setForeground(new java.awt.Color(20, 17, 96));

        quionaitemstatus.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        quionaitemstatus.setForeground(new java.awt.Color(20, 17, 96));

        pancakeitemstatus.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        pancakeitemstatus.setForeground(new java.awt.Color(20, 17, 96));

        expressoitemstatus.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        expressoitemstatus.setForeground(new java.awt.Color(20, 17, 96));

        sandwitchitemstatus.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        sandwitchitemstatus.setForeground(new java.awt.Color(20, 17, 96));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(backbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ordertotal)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(checkoutbutton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(ordertotaltextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(63, 63, 63))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(choosecusine)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cusinetypes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(sno)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(pancakeitem)
                                            .addComponent(sandwitchitem)
                                            .addComponent(expressoitem)
                                            .addComponent(quionaitem)
                                            .addComponent(chickenitem))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(46, 46, 46)
                                                .addComponent(quantitycombo5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(quantitycombo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(quantitycombo2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(quantitycombo3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(quantitycombo4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(57, 57, 57)
                                        .addComponent(item)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(quantity))))
                            .addComponent(sno4)
                            .addComponent(sno5, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sno3, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sno2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sno1))))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(unitprice)
                    .addComponent(unitpricetext1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unitpricetext2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unitpricetext3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unitpricetext4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unitpricetext5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(subtotaltext5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subtotal)
                    .addComponent(subtotaltext1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(subtotaltext4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(calculatebutton)
                        .addGap(65, 65, 65)
                        .addComponent(resetbutton))
                    .addComponent(subtotaltext3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subtotaltext2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(chickenorderstatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(quionaitemstatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(sandwitchitemstatus, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                                        .addComponent(expressoitemstatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(pancakeitemstatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(51, 141, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(orderstatus)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(applycouponcode, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(choosecusine)
                    .addComponent(cusinetypes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(orderstatus)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sno)
                            .addComponent(item)
                            .addComponent(unitprice)
                            .addComponent(quantity)
                            .addComponent(subtotal)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(chickenorderstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sno1)
                            .addComponent(chickenitem)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(quantitycombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(unitpricetext1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(subtotaltext1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sno2)
                            .addComponent(quionaitem)
                            .addComponent(quantitycombo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(unitpricetext2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subtotaltext2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sno3)
                            .addComponent(pancakeitem)
                            .addComponent(quantitycombo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(unitpricetext3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subtotaltext3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(sno4)
                                    .addComponent(expressoitem)
                                    .addComponent(quantitycombo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(unitpricetext4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(subtotaltext4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(calculatebutton)
                                    .addComponent(resetbutton))
                                .addGap(25, 25, 25)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sno5)
                            .addComponent(sandwitchitem)
                            .addComponent(quantitycombo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(unitpricetext5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subtotaltext5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(quionaitemstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pancakeitemstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(expressoitemstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sandwitchitemstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(applycouponcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ordertotal)
                    .addComponent(ordertotaltextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(backbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(checkoutbutton)
                .addGap(57, 57, 57))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cusinetypesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusinetypesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cusinetypesActionPerformed

    private void resetbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbuttonActionPerformed
        // TODO add your handling code here:
       //we can create by default the values are null. 
       unitpricetext1.setText(null);
       unitpricetext2.setText(null);
       unitpricetext3.setText(null);
       unitpricetext4.setText(null);
       unitpricetext5.setText(null);
         subtotaltext1.setText(null);
         subtotaltext2.setText(null);
         subtotaltext3.setText(null);
         subtotaltext4.setText(null);
         subtotaltext5.setText(null);     
    }//GEN-LAST:event_resetbuttonActionPerformed

    private void calculatebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculatebuttonActionPerformed
        // TODO add your handling code here:
        //how much quantity you want by declareing here.
        double Quantity1 =Double.parseDouble((String) quantitycombo1.getSelectedItem());
        double Quantity2 =Double.parseDouble((String) quantitycombo2.getSelectedItem());
        double Quantity3 =Double.parseDouble((String) quantitycombo3.getSelectedItem());
        double Quantity4 =Double.parseDouble((String) quantitycombo4.getSelectedItem());
        double Quantity5 =Double.parseDouble((String) quantitycombo5.getSelectedItem());
        
        double total,subTotal,Addup,subTotal1,subTotal2,subTotal3,subTotal4,subTotal5;
        
        //performing selected quantity to unit price.
        String chicken_burger=String.format("%.2f",fooditems[0]);
        unitpricetext1.setText(chicken_burger);
        String quino_and=String.format("%.2f",fooditems[1]);
        unitpricetext2.setText(quino_and);
        String pan_cakes=String.format("%.2f",fooditems[2]);
        unitpricetext3.setText(pan_cakes);
        String express=String.format("%.2f",fooditems[3]);
        unitpricetext4.setText(express);
        String sand=String.format("%.2f",fooditems[4]);
        unitpricetext5.setText(sand);
        
        //it is performing multiplication operation. between quantity and unit price.
        subTotal1 =Quantity1 * fooditems[0];
         subTotal2 =Quantity2 * fooditems[1];
          subTotal3 =Quantity3 * fooditems[2];
           subTotal4 =Quantity4 * fooditems[3];
            subTotal5 =Quantity5 * fooditems[4];
        //it is makeing the after calculation of the values are shown in subtotal 
        
          String sub1=String.format("%.2f",subTotal1);
        subtotaltext1.setText(sub1);
        String sub2=String.format("%.2f",subTotal2);
        subtotaltext2.setText(sub2);
        String sub3 =String.format("%.2f",subTotal3);
        subtotaltext3.setText(sub3);
        String sub4=String.format("%.2f",subTotal4);
        subtotaltext4.setText(sub4);
        String sub5=String.format("%.2f",subTotal5);
        subtotaltext5.setText(sub5);
        
        subTotal=subTotal1+subTotal2+subTotal3+subTotal4+subTotal5;
        
        String subTotalAll=String.format("%.2f", subTotal);
        ordertotaltextfield.setText(subTotalAll);
        
        if(chickenitem.isSelected())
            chickenorderstatus.setText("chickenburg5er with bacon");
        else
            chickenorderstatus.setText("");
        
        if(quionaitem.isSelected())
            quionaitemstatus.setText("Quiona and kale");
        else
            quionaitemstatus.setText("");
        
        if(pancakeitem.isSelected())
            pancakeitemstatus.setText("Pancakes with maple syrup");
        else
            pancakeitemstatus.setText("");
        
        if(expressoitem.isSelected())
            expressoitemstatus.setText("Expresso");
        else
            expressoitemstatus.setText("");
        
        if(sandwitchitem.isSelected())
            sandwitchitemstatus.setText("SandWitch");
        else
            sandwitchitemstatus.setText("");
    
       
    }//GEN-LAST:event_calculatebuttonActionPerformed

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        myacccount ob=new myacccount();
        ob.setVisible(true);
        
    }//GEN-LAST:event_backbuttonActionPerformed

    private void checkoutbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutbuttonActionPerformed
        // TODO add your handling code here:
        
        //it is used tomake one value in this screen to another screen.
        String msg = ordertotaltextfield.getText();
        String chi1 = chickenorderstatus.getText();
        String quiona1 = quionaitemstatus.getText();
        String pan1 = pancakeitemstatus.getText();
        String exp1 = expressoitemstatus.getText();
        String san1 = sandwitchitemstatus.getText();
       
       
        
        new checkout(msg,chi1,quiona1,pan1,exp1,san1).setVisible(true);
        
        
        
    }//GEN-LAST:event_checkoutbuttonActionPerformed

    private void ordertotaltextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordertotaltextfieldActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_ordertotaltextfieldActionPerformed

    private void quionaitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quionaitemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quionaitemActionPerformed

    private void quantitycombo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantitycombo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantitycombo2ActionPerformed

    private void subtotaltext4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtotaltext4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subtotaltext4ActionPerformed

    private void subtotaltext3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtotaltext3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subtotaltext3ActionPerformed

    private void subtotaltext2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtotaltext2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subtotaltext2ActionPerformed

    private void chickenitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chickenitemActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_chickenitemActionPerformed

    private void sandwitchitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sandwitchitemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sandwitchitemActionPerformed

    private void unitpricetext4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unitpricetext4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unitpricetext4ActionPerformed

    private void quantitycombo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantitycombo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantitycombo3ActionPerformed

    private void unitpricetext2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unitpricetext2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unitpricetext2ActionPerformed

    private void quantitycombo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantitycombo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantitycombo1ActionPerformed

    private void unitpricetext3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unitpricetext3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unitpricetext3ActionPerformed

    private void subtotaltext5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtotaltext5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subtotaltext5ActionPerformed

    private void unitpricetext5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unitpricetext5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unitpricetext5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }
// Variables declaration - do not modify ("Encapsulation")
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField applycouponcode;
    private javax.swing.JButton backbutton;
    private javax.swing.JButton calculatebutton;
    private javax.swing.JButton checkoutbutton;
    private javax.swing.JCheckBox chickenitem;
    private javax.swing.JLabel chickenorderstatus;
    private javax.swing.JLabel choosecusine;
    private javax.swing.JComboBox<String> cusinetypes;
    private javax.swing.JCheckBox expressoitem;
    private javax.swing.JLabel expressoitemstatus;
    private javax.swing.JLabel item;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel orderstatus;
    private javax.swing.JLabel ordertotal;
    private javax.swing.JTextField ordertotaltextfield;
    private javax.swing.JCheckBox pancakeitem;
    private javax.swing.JLabel pancakeitemstatus;
    private javax.swing.JLabel quantity;
    private javax.swing.JComboBox<String> quantitycombo1;
    private javax.swing.JComboBox<String> quantitycombo2;
    private javax.swing.JComboBox<String> quantitycombo3;
    private javax.swing.JComboBox<String> quantitycombo4;
    private javax.swing.JComboBox<String> quantitycombo5;
    private javax.swing.JCheckBox quionaitem;
    private javax.swing.JLabel quionaitemstatus;
    private javax.swing.JButton resetbutton;
    private javax.swing.JCheckBox sandwitchitem;
    private javax.swing.JLabel sandwitchitemstatus;
    private javax.swing.JLabel sno;
    private javax.swing.JLabel sno1;
    private javax.swing.JLabel sno2;
    private javax.swing.JLabel sno3;
    private javax.swing.JLabel sno4;
    private javax.swing.JLabel sno5;
    private javax.swing.JLabel subtotal;
    private javax.swing.JTextField subtotaltext1;
    private javax.swing.JTextField subtotaltext2;
    private javax.swing.JTextField subtotaltext3;
    private javax.swing.JTextField subtotaltext4;
    private javax.swing.JTextField subtotaltext5;
    private javax.swing.JLabel unitprice;
    private javax.swing.JTextField unitpricetext1;
    private javax.swing.JTextField unitpricetext2;
    private javax.swing.JTextField unitpricetext3;
    private javax.swing.JTextField unitpricetext4;
    private javax.swing.JTextField unitpricetext5;
    // End of variables declaration//GEN-END:variables
}
