/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapp;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author utpl-4
 */
public class myacccount extends load {
        Connection conn;
ResultSet rs;
PreparedStatement pst;
    
   

    /**
     * Creates new form myacccount
     */
    public myacccount() {
        initComponents();
        conn=javaconnect.ConnecrDb();
    }
         
    

      public void Search(){
        String a1=FullnameTextField.getText();
        String sql="select * from foods where Username='"+a1+"'";
        try{
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
        if(rs.next()){
            UserNameTextField.setText(rs.getString(1));
            rs.close();
            pst.close();
        }
        else{
            JOptionPane.showMessageDialog(null, "Incorrect Username");
        }
        }catch(Exception e){
               JOptionPane.showMessageDialog(null, e);
        }
    }
    
   

    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        logoutButton = new javax.swing.JButton();
        ProceedButton = new javax.swing.JButton();
        EditDetailsButton = new javax.swing.JButton();
        Welcome = new javax.swing.JLabel();
        foodImg = new javax.swing.JLabel();
        MyaccountText = new javax.swing.JLabel();
        RecentOrders = new javax.swing.JButton();
        TransactionsButtons = new javax.swing.JButton();
        MessageButton = new javax.swing.JButton();
        statisticsButton = new javax.swing.JButton();
        AccountButtton = new javax.swing.JButton();
        FullnameTextField = new javax.swing.JTextField();
        UserNameTextField = new javax.swing.JTextField();
        AnswerTextField = new javax.swing.JTextField();
        UserName = new javax.swing.JLabel();
        fullName = new javax.swing.JLabel();
        Sec_Q = new javax.swing.JLabel();
        Answer = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        sec_QComboBox = new javax.swing.JComboBox<>();
        Save = new javax.swing.JButton();
        PasswordField = new javax.swing.JPasswordField();
        EditDetails = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(78, 205, 196));

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(161, 32, 33));
        jLabel1.setText("7 FOOD COURT ORDERING SYSTEM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(194, 189, 148));
        jPanel2.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N

        logoutButton.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(6, 78, 7));
        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        ProceedButton.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        ProceedButton.setForeground(new java.awt.Color(6, 78, 7));
        ProceedButton.setText("Proceed");
        ProceedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProceedButtonActionPerformed(evt);
            }
        });

        EditDetailsButton.setBackground(new java.awt.Color(221, 78, 4));
        EditDetailsButton.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        EditDetailsButton.setText("Edit Details");
        EditDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditDetailsButtonActionPerformed(evt);
            }
        });

        Welcome.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        Welcome.setForeground(new java.awt.Color(176, 22, 22));
        Welcome.setText("#WELCOME");

        foodImg.setIcon(new javax.swing.ImageIcon("/home/utpl/Desktop/7FoodCourtordering/food-ordering.png")); // NOI18N

        MyaccountText.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        MyaccountText.setForeground(new java.awt.Color(10, 105, 14));
        MyaccountText.setText("My Account");

        RecentOrders.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        RecentOrders.setText("Recent Orders");
        RecentOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecentOrdersActionPerformed(evt);
            }
        });

        TransactionsButtons.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        TransactionsButtons.setText("Transactions");

        MessageButton.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        MessageButton.setText("Messages");

        statisticsButton.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        statisticsButton.setText("Statistics");

        AccountButtton.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        AccountButtton.setText("Accounts");

        AnswerTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnswerTextFieldActionPerformed(evt);
            }
        });

        UserName.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        UserName.setForeground(new java.awt.Color(26, 120, 27));
        UserName.setText("User Name:");

        fullName.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        fullName.setForeground(new java.awt.Color(26, 120, 27));
        fullName.setText("Full Name:");

        Sec_Q.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        Sec_Q.setForeground(new java.awt.Color(26, 120, 27));
        Sec_Q.setText("Security Question:");

        Answer.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        Answer.setForeground(new java.awt.Color(26, 120, 27));
        Answer.setText("Answer:");

        password.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        password.setForeground(new java.awt.Color(26, 120, 27));
        password.setText("Password:");

        sec_QComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What is your mother Tongue.?", "What is your nick name.?", "who is your first Childhood friend.?", "What is your Pet name.?" }));

        Save.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        Save.setForeground(new java.awt.Color(6, 78, 7));
        Save.setText("SAVE");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        EditDetails.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        EditDetails.setForeground(new java.awt.Color(6, 78, 7));
        EditDetails.setText("Edit Details.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(foodImg, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(RecentOrders)
                                    .addComponent(TransactionsButtons)
                                    .addComponent(MessageButton))
                                .addGap(48, 48, 48))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(MyaccountText)
                                .addGap(10, 10, 10)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(UserName, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Sec_Q, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(password, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Answer, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(fullName, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(EditDetailsButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(statisticsButton)
                                .addGap(70, 70, 70)
                                .addComponent(AccountButtton)
                                .addGap(9, 9, 9))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EditDetails)
                                    .addComponent(Save, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(FullnameTextField)
                                        .addComponent(UserNameTextField)
                                        .addComponent(AnswerTextField)
                                        .addComponent(PasswordField)
                                        .addComponent(sec_QComboBox, 0, 285, Short.MAX_VALUE)))
                                .addGap(0, 33, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(Welcome)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(ProceedButton)
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 79, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(statisticsButton)
                            .addComponent(AccountButtton)
                            .addComponent(EditDetailsButton)
                            .addComponent(MyaccountText))
                        .addGap(66, 66, 66)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FullnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fullName)
                            .addComponent(RecentOrders))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UserNameTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(UserName)
                                .addComponent(TransactionsButtons)))
                        .addGap(31, 31, 31))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Welcome)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(EditDetails)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(foodImg, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(MessageButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sec_QComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Sec_Q))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AnswerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Answer)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(password))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(Save, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(ProceedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1109, 741));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
         Log ob=new Log();
         ob.setVisible(true);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void ProceedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProceedButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Menu ob=new Menu();
        ob.setVisible(true);
        
    }//GEN-LAST:event_ProceedButtonActionPerformed

    private void EditDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditDetailsButtonActionPerformed
        // TODO add your handling code here:
        //the search declared here.
        Search();
     
        
    }//GEN-LAST:event_EditDetailsButtonActionPerformed

    private void AnswerTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnswerTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AnswerTextFieldActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
        
        //if you want to change your values you can insert instead of that
        try{
          String sql="Insert into foods(Fullname,Username,Password,Sec_Q,Answer) values(?,?,?,?,?)";
          pst=conn.prepareStatement(sql);
          pst.setString(1, UserNameTextField.getText());
          pst.setString(2, FullnameTextField.getText());
          pst.setString(3, PasswordField.getText());
          pst.setString(4, (String) sec_QComboBox.getSelectedItem());
          pst.setString(5, AnswerTextField.getText());
          pst.execute();
          JOptionPane.showMessageDialog(null, "Account Updated");
      }catch(Exception e){
          JOptionPane.showMessageDialog(null, e);
      } 
        
    }//GEN-LAST:event_SaveActionPerformed

    private void RecentOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecentOrdersActionPerformed
        // TODO add your handling code here:
     setVisible(false);
         myorder ob=new myorder();
         ob.setVisible(true);
    }//GEN-LAST:event_RecentOrdersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(myacccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(myacccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(myacccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(myacccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new myacccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AccountButtton;
    private javax.swing.JLabel Answer;
    private javax.swing.JTextField AnswerTextField;
    private javax.swing.JLabel EditDetails;
    private javax.swing.JButton EditDetailsButton;
    private javax.swing.JTextField FullnameTextField;
    private javax.swing.JButton MessageButton;
    private javax.swing.JLabel MyaccountText;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JButton ProceedButton;
    private javax.swing.JButton RecentOrders;
    private javax.swing.JButton Save;
    private javax.swing.JLabel Sec_Q;
    private javax.swing.JButton TransactionsButtons;
    private javax.swing.JLabel UserName;
    private javax.swing.JTextField UserNameTextField;
    private javax.swing.JLabel Welcome;
    private javax.swing.JLabel foodImg;
    private javax.swing.JLabel fullName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel password;
    private javax.swing.JComboBox<String> sec_QComboBox;
    private javax.swing.JButton statisticsButton;
    // End of variables declaration//GEN-END:variables
}
